### ISSUE TITLE
Add compile-time checks for JS backend

### ISSUE THREAD

**Issue by thatrandomperson5** [Vindaar/LatexDSL#16]
Currently the entire “LaTeX compiler and configuration files” part prevents latexdsl from compiling frontend. It would be appreciated if some `when not defined(js)` could be added for those parts so the DSL could still be used with the JS backend.

In my situation I am currently getting an error [here](https://github.com/Vindaar/LatexDSL/blob/master/src/latexdsl/latex_helpers.nim#L54) but I am pretty sure the same issue applies to other parts.

**Comment by Vindaar** [comment]
Ah, fair point! I'll see what I can do. Should be pretty straightforward.

**Comment by Vindaar** [comment]
Will be taken care of by #17.
